### ISSUE TITLE
ROS packages

### ISSUE THREAD

**Issue by FrankyForkFingerz** [MoebiusTech/Stm32f103rct6#2]
Hello,
Do you can provide the ROS packages for that board?

I want to use it on a raspberry pi4 with ROS catkin melodic.

Or maybe a whole image for a raspberry pi4 with a working ROS like you made for the raspberry pi3.

Thank you in advance.

**Comment by danielespitiacol** [comment]
Hi Franky, I have the same problem.
-  I have installed ROS kinetic in the PC and flashed the ubuntu mate image (provided by google drive) to the raspberry pi, and setup the ros network successfully.
- I have plugged the SMT32 board to the raspberry by USB and checked mbsbase port appear in the /dev/ directory succesfully.
- When I run "roslaunch mbsrobot bringup.launch", I have the error: Unable to sync with device.

I think the board is not programmed from factory to comunicate with ROS.

**Comment by guronutf8** [comment]
> Hi Franky, I have the same problem.
> 
> * I have installed ROS kinetic in the PC and flashed the ubuntu mate image (provided by google drive) to the raspberry pi, and setup the ros network successfully.
> * I have plugged the SMT32 board to the raspberry by USB and checked mbsbase port appear in the /dev/ directory succesfully.
> * When I run "roslaunch mbsrobot bringup.launch", I have the error: Unable to sync with device.
> 
> I think the board is not programmed from factory to comunicate with ROS.

https://github.com/MoebiusTech/ROS_STM32/blob/main/STM32_Ros_master_melodic-lib.7z I figured it out, I need to reflash to work with ROS

**Comment by danielespitiacol** [comment]
Thank you guronutf8

I have flashed, but now I have this problem:
[ERROR] Creation of publisher failed: riki_msgs
[ERROR] Tried to publish before configurated, topic id 126

**Comment by guronutf8** [comment]
> Thank you guronutf8
> 
> I have flashed, but now I have this problem:
> [ERROR] Creation of publisher failed: riki_msgs
> [ERROR] Tried to publish before configurated, topic id 126

examine the file config.h.
Pay attention to #define ROSVERSION 2 (3 noetic doesn't work, i.e. 1 or 2)
if 1. you need to add riki_msgs to your satkin_bs search in Google.
Or 2, copy the mbs_msgs directory to your catkin_vs

Further:
in CMakeLists.txt add find_package (
***
   mbs_msgs
***
)
further: catkin_make


ps mbs_msgs "Install the MBS environment on your own Linux\catkin_ws\src\mbsrobot_project\mbs_msgs\" from
https://drive.google.com/drive/folders/1FbEeWd4VyqahfnX3yiib85Xs_cBSabZK

**Comment by guronutf8** [comment]
ps links to google drive found here https://github.com/MoebiusTech/ROS_STM32

**Comment by danielespitiacol** [comment]
> > Thank you guronutf8
> > I have flashed, but now I have this problem:
> > [ERROR] Creation of publisher failed: riki_msgs
> > [ERROR] Tried to publish before configurated, topic id 126
> 
> examine the file config.h.
> Pay attention to #define ROSVERSION 2 (3 noetic doesn't work, i.e. 1 or 2)
> if 1. you need to add riki_msgs to your satkin_bs search in Google.
> Or 2, copy the mbs_msgs directory to your catkin_vs
> 
> Further:
> in CMakeLists.txt add find_package (
> 
> mbs_msgs
> 
> )
> further: catkin_make
> 
> ps mbs_msgs "Install the MBS environment on your own Linux\catkin_ws\src\mbsrobot_project\mbs_msgs" from
> https://drive.google.com/drive/folders/1FbEeWd4VyqahfnX3yiib85Xs_cBSabZK

Now it works!
I am using kinetic and I downloaded riki_msgs from: https://github.com/dwz9406/rikirobot/tree/master/catkin_ws/src/rikirobot_project/riki_msgs
I have copied it in the catkin_ws/src folder and run: 	
        cd ~/catkin_ws
	catkin_make -j1
Thank you for your help

**Comment by mattkanwisher** [comment]
Is there some info on how you flash the STM32? I see a bunch of windows programs, is there any way to do this from linux? Is there a specific file we need to give to the flasher?

**Comment by FrankyForkFingerz** [comment]
Hello guys,

Last weekend finally I managed the board to work on a Raspberry Pi4 with an Ubuntu 20.04 and ROS Noetic.

Thanks @guronutf8 for the tip of reflashing and thanks @danielespitiacol for the link of the riki_msgs.

@mattkanwisher
This is the link of the software you have to flash: https://github.com/MoebiusTech/Stm32f103rct6/commit/3c39522138b9a6083eaf70917c4e10324b2d4840#diff-1bb6a2ad3de12d8b44050e2a2b9e158f06c0a4ff938486471b69dc42d707c5c8

Important is to flash the right version according to your rosversion, pay attention to #define ROSVERSION, like guronutf8 wrote.

KEIL is the software of choice to flash, how it works on linux I don’t know but easiest would be to generate a virtual machine with windows 10 and KEIL for ARM.

@danielespitiacol
You wrote: “I have installed ROS kinetic in the PC and flashed the ubuntu mate image (provided by google drive) to the raspberry pi, and setup the ros network successfully.”

Do you use a ROS Master and a Slave?

Best regards

**Comment by danielespitiacol** [comment]
> Hello guys,
> 
> Last weekend finally I managed the board to work on a Raspberry Pi4 with an Ubuntu 20.04 and ROS Noetic.
> 
> Thanks @guronutf8 for the tip of reflashing and thanks @danielespitiacol for the link of the riki_msgs.
> 
> @mattkanwisher
> This is the link of the software you have to flash: [3c39522#diff-1bb6a2ad3de12d8b44050e2a2b9e158f06c0a4ff938486471b69dc42d707c5c8](https://github.com/MoebiusTech/Stm32f103rct6/commit/3c39522138b9a6083eaf70917c4e10324b2d4840#diff-1bb6a2ad3de12d8b44050e2a2b9e158f06c0a4ff938486471b69dc42d707c5c8)
> 
> Important is to flash the right version according to your rosversion, pay attention to #define ROSVERSION, like guronutf8 wrote.
> 
> KEIL is the software of choice to flash, how it works on linux I don’t know but easiest would be to generate a virtual machine with windows 10 and KEIL for ARM.
> 
> @danielespitiacol
> You wrote: “I have installed ROS kinetic in the PC and flashed the ubuntu mate image (provided by google drive) to the raspberry pi, and setup the ros network successfully.”
> 
> Do you use a ROS Master and a Slave?
> 
> Best regards

@FrankyForkFingerz 
I´m running roscore in a PC with windows 10 and a virtual machine running Ubuntu 16.04 and ros kinetic. The raspberry and the PC are in the same wifi network.

Best regards

**Comment by juvinski** [comment]
hi @FrankyForkFingerz ,

 
Are you sure the version on the link you posted ? because on that link ther e is just the ps controller code - not the ROS.
What I found was on the other repository: https://github.com/MoebiusTech/ROS_STM32/blob/main/STM32_Ros_master_melodic-lib.7z

**Comment by nofiyanaj** [comment]
what is mbsrobot ubuntu root password?

**Comment by MoebiusTech** [comment]
password：123456



***@***.***
 
From: nofiyanaj
Date: 2021-10-24 14:47
To: MoebiusTech/Stm32f103rct6
CC: Subscribed
Subject: Re: [MoebiusTech/Stm32f103rct6] ROS packages (#2)
what is mbsrobot ubuntu root password?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
